'use client';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import { roboto } from '@/app/ui/fonts';
import { lato } from '@/app/ui/fonts'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
export default function Login() {
  return (
      <div className={`flex justify-center flex-col w-full mt-14 ${lato.className}`}>
          <p>Login Page</p>
      </div>
  )
}